kafka:
  replicas: 1 # 5
  listeners:
    - name: PLAINTEXT
      port: 9092
      protocol: PLAINTEXT
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    size: "10Gi"

topics:
  - name: sessions
    partitions: 3
    replication-factor: 1  
    configs:
      retention.ms: 604800000  # 7 days
      cleanup.policy: delete

  - name: raw-frames
    partitions: 6 # 24
    replication-factor: 1 # 3
    configs:
      retention.ms: 86400000  # 24 hours
      cleanup.policy: delete
      compression.type: lz4
  