apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image }}
        command: ["bash", "-c"]
        args:
          - |
            cd /app
            pip install -r requirements.txt
            uvicorn app.main:app --reload
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.fastapi.kafka.bootstrapServers }}
        volumeMounts:
        - name: source-code
          mountPath: {{ .Values.fastapi.sourceCode.containerPath }}
      volumes:
      - name: source-code
        hostPath:
          path: {{ .Values.fastapi.sourceCode.hostPath }}
          type: Directory