apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: 9092
    protocol: TCP
    name: kafka
  selector:
    app: {{ .Release.Name }}-kafka